defaults: &defaults
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  pool: 5
  port: 5432
  username: john

development:
  database: blockbyblocks_dev
  <<: *defaults

test:
  database: blockbyblocks_test
  <<: *defaults
